apiVersion: serving.knative.dev/v1
kind: Service
metadata:
  name: pl-serverless
  namespace: userx-piglatin
spec:
  template:
    spec:
      containers:
        - image: image-registry.openshift-image-registry.svc:5000/userx-piglatin/piglatin-app:latest
          env:
            - name: SLACK_SIGNING_SECRET
              valueFrom:
                secretKeyRef:
                  name: slack-signing-secret
                  key: SLACK_SIGNING_SECRET
